/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, LandingPage as PrismaLandingPage } from "@prisma/client";

export class LandingPageServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.LandingPageCountArgs, "select">
  ): Promise<number> {
    return this.prisma.landingPage.count(args);
  }

  async landingPages<T extends Prisma.LandingPageFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.LandingPageFindManyArgs>
  ): Promise<PrismaLandingPage[]> {
    return this.prisma.landingPage.findMany<Prisma.LandingPageFindManyArgs>(
      args
    );
  }
  async landingPage<T extends Prisma.LandingPageFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.LandingPageFindUniqueArgs>
  ): Promise<PrismaLandingPage | null> {
    return this.prisma.landingPage.findUnique(args);
  }
  async createLandingPage<T extends Prisma.LandingPageCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.LandingPageCreateArgs>
  ): Promise<PrismaLandingPage> {
    return this.prisma.landingPage.create<T>(args);
  }
  async updateLandingPage<T extends Prisma.LandingPageUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.LandingPageUpdateArgs>
  ): Promise<PrismaLandingPage> {
    return this.prisma.landingPage.update<T>(args);
  }
  async deleteLandingPage<T extends Prisma.LandingPageDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.LandingPageDeleteArgs>
  ): Promise<PrismaLandingPage> {
    return this.prisma.landingPage.delete(args);
  }
}
